### ISSUE TITLE
v4 -> v3 Code Example/Retain Question

### ISSUE THREAD

**Issue by joshavant** [ReactiveKit/Bond#158]
I have a question on the [Bindings > NSObject](https://github.com/joshavant/Bond/tree/documentation-update-20150925#nsobject) example?

To start, let's call the first code example (the one with the `print` call) Example A.

I don't see why the fact that `viewModel` outlives the the View Controller means that I need to manually dispose of the observation.

It would seem (under v3 memory conventions, at least) that the closure would be the one responsible for retaining `viewModel.name` and, presumably, the closure would get autoreleased at the end of `viewDidLoad`.

I can't figure out how, in this example, `viewModel` and View Controller memory lifetimes are related, and what, in any of that implementation, requires the manual observation disposal.

Do you think you could offer any guidance on what I might be missing? I'd really appreciate it!

**Comment by srdanrasic** [comment]
Given that the view model instance outlives the view controller, think of what would happen if you do not dispose the observation. If you do only the following in `viewDidLoad`:

```swift
viewModel.name
      .observe { name in
        print(name)
      }
```

Everything would still work, but name changes would be printed even when your view controller gets destroyed.

In v3 we had that unfortunate `Bond` class that was managing binding/observing, keeping it alive as long as the Bond instance is alive. 

In v4 everything is changed and _observings/bindings are alive until they are disposed_. UIKit extensions will automatically dispose bindings when they are destroyed. For example, anything binding to UILabel's `bnd_text` property will be disposed when that label is destroyed. 

That being said, you usually don't want your view models outliving the view controllers. If you stick to that rule, you won't have to worry about disposing observers.

**Comment by srdanrasic** [comment]
Another way is to look at the method signature. Any observer is registered with following method:

```swift
func observe(observer: EventType -> Void) -> DisposableType
```

The closure we pass in there will stay registered until dispose() is called on the returned disposable.

**Comment by joshavant** [comment]
@srdanrasic Thanks for your helpful reply! That helped a lot to clarify.

Re: [your first comment](https://github.com/SwiftBond/Bond/issues/158#issuecomment-143160284) - Sorry, is the call to `print` in the code example a class method inside the view controller or the [Swift Standard Library function](https://developer.apple.com/library/ios//documentation/Swift/Reference/Swift_StandardLibrary_Functions/index.html#//apple_ref/swift/func/s:FSs5printFTGSaP__9separatorSS10terminatorSS_T_) (i.e. the old `println` from Swift 1.2)?

Also, in our app's architecture, our view controllers don't necessarily have knowledge of whether the view model will outlive the view controller. Does this mean we would have to append `.disposeIn(bnd_bag)` to all view model bindings, in this case?

Re: [your second comment](https://github.com/SwiftBond/Bond/issues/158#issuecomment-143194871) - Just to be sure I understand, are you saying the closure that's passed into `observer()` will be strongly retained by the receiver (i.e. the `EventProducer`) until `dispose()` is called?

**Comment by srdanrasic** [comment]
`print` is part of Swift 2.0 standard library. `println` is deprecated.

> Also, in our app's architecture, our view controllers don't necessarily have knowledge of whether the view model will outlive the view controller. Does this mean we would have to append `.disposeIn(bnd_bag)` to all view model bindings, in this case?

You would have to manually dispose observations made with `observe` method. You would not have to manually dispose bindings established with `bindTo` method because those are disposed automatically.

I see you understand the `observe` method correctly:

> Just to be sure I understand, are you saying the closure that's passed into observer() will be strongly retained by the receiver (i.e. the EventProducer) until dispose() is called?

That's right.

Method `bindTo` uses `observe` internally, but also handles the disposable by attaching it to the passed bindable object so it gets disposed when the bindable is destroyed.

Here is how it works. Anything that conforms to the `BindableType` can be passed into `bindTo` method of an `Observable` (`EventProducer`). `BindableType` protocol defines one method that can be used to get a sink (a closure) used to send events to that object. It accepts a `Disposable` that it should dispose when it's destroyed.

```swift
public protocol BindableType {
  typealias Element
  
  /// Returns a sink that can be used to dispatch events to the receiver.
  /// Can accept a disposable that will be disposed on receiver's deinit.
  func sink(disconnectDisposable: DisposableType?) -> (Element -> ())
}
```

Now to `bindTo` method. It receives an object conforming to `BindableType` protocol. First, it creates a Serial Disposable. It's a disposable that can dispose itself plus some other disposable. Then is gets the `sink` from the received object passing it the serial disposable at the same time. That means that when the `bindable` gets destroyed it will also dispose our serial disposable. Next, we register an observer that passes events to the `bindable` using the given `sink` and we save the returned disposable as the other disposable of our serial disposable. In effect, `observe`'s disposable will be disposed when the serial disposable gets disposed and as I already said, serial disposable will be disposed when the `bindable` is destroyed. Finally, serial disposable is returned if you, for some reason, want to cancel binding before the `bindable` is destroyed.

```swift
public extension EventProducerType {
  public func bindTo<B: BindableType where B.Element == EventType>(bindable: B) -> DisposableType {
    let disposable = SerialDisposable(otherDisposable: nil)
    let sink = bindable.sink(disposable)
    disposable.otherDisposable = observe { value in
      sink(value)
    }
    return disposable
  }
}
```

`EventProducer` (and so `Observable`) conforms to `BindableType` and UIKit extensions are just plain `Observables` so you get automatic disposing out of the box.

Hope this helps.

**Comment by joshavant** [comment]
Aha! Ok, I get it now!

Thank you so much for the helpful reply and the awesome work with Bond. :)

**Comment by srdanrasic** [comment]
Closed as outdated.
