### ISSUE TITLE
iOS 7 support?

### ISSUE THREAD

**Issue by zdenektopic** [ReactiveKit/Bond#215]
Will Bond (and/or ReactiveKit) work on iOS 7?
I am talking about installation via CocoaSeeds - https://github.com/devxoul/CocoaSeeds

**Comment by srdanrasic** [comment]
Hmm, looking at it. You have to specifies files. Problem is that Bond has both iOS and OSX source files in its root sources directory so the matching pattern would be complex.

I think that getting ReactiveKit to work with it would be simpler as it does not contain OSX files.

**Comment by zdenektopic** [comment]
I have big iOS project that needs to support iOS 7 as it represents a lot of targeted users and I really, I mean I REALLY would like to use Bonds or ReactiveKits observables and UI extensions. I would use ReactiveCocoa, but to be honest it seems too complicated for simple things like reacting to value change in model.

**Comment by zdenektopic** [comment]
And actually I wanted to know if it will work with iOS7 without any troubles.

**Comment by srdanrasic** [comment]
I've investigated CocoaSeeds further. Their idea of stripping project file and using only sources will not work with Bond or ReactiveKit. Project files contain necessary compiler information and parameters without which frameworks won't compile well. It's not that easy.

Also, the code would probably work on iOS7 because frameworks are not relying on any often changing APIs, but I cannot provide any official support.

It's unfortunate that iOS 7 represents a lot of targeted users for you. Looking at Mixpanel stats, there is less than 5% of devices that are on pre-iOS8 version globally. In few months when you're done with the app it will be even less.

If you really want to use Bond or ReactiveKit the easiest way would be to fork them, lower the deployment target to iOS7 and use the fork with either plain Git submodules or with Carthage.
