### ISSUE TITLE
Tableview header implementation

### ISSUE THREAD

**Issue by JuGoo** [ReactiveKit/Bond#220]
Hi,

I am making an application in which a header of tableview view is required. I am using Bond framework to bind the datasource with the tableview view. 
It was working fine until I tried to get titleForHeaderInSection for the headers. 
I can't print a header like a alphabetical header. (like here http://www.appcoda.com/ios-programming-index-list-uitableview/) I tried use BNDTableViewProxyDataSource protocol.

An exemple of code should be enough.

Thanks in advance for your help.

**Comment by srdanrasic** [comment]
Hi @JuGoo, could you post your code here? It should work like in that example. Just don't implement UITableViewDataSource but a BNDTableViewProxyDataSource - it has same methods.

**Comment by JuGoo** [comment]
Sure,

for example my data is:
var list = ["Vegetables": ["Carrot", "Potato", "Radish"], "Fruits": ["Apple", "Banana"] ...]

var dataSource = ObservableArray<ObservableArray<NSArray>>()

in viewDidLoad

dataSourceSection.bindTo(tableView) { (indexPath, dataSource, tableView) -> UITableViewCell in
            let cell = tableView.dequeueReusableCellWithIdentifier("cell", forIndexPath: indexPath)!
            let viewModel = dataSource[indexPath.section][indexPath.row]
           
            return cell
        }

and extension

extension MyViewController: BNDTableViewProxyDataSource {
    override func tableView(tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        //return "Header"
        //here i would return section name like Vegetables, Fruits...
    }
}

**Comment by srdanrasic** [comment]
You have to pass instance that implements BNDTableViewProxyDataSource into bindTo method.

```swift
dataSourceSection.bindTo(tableView, proxyDataSource: self)...
```

**Comment by JuGoo** [comment]
Ok, now i use that:
dataSource.bindTo(outletTableView, proxyDataSource: self) { (indexPath, dataSource, tableView) -> UITableViewCell in
            let cell = (tableView.dequeueReusableCellWithIdentifier("cell", forIndexPath: indexPath) as? SettingsMenuTableViewCell)!
            
            let viewModel = dataSource[indexPath.section][indexPath.row]
            print(viewModel)
            return cell
        }

So, how can set title for header?
Thank's in advance @srdanrasic

**Comment by pk1** [comment]
Hi,

I'm adding my question to this issue because the main topic seems to be more or less the same (regarding section titles).
In my implementation I have a tabbar with several buttons each of them triggering a search which will fill the table view with the appropriate data. Depending on the selected tabbar button the table will contain\show different sections. I have implemented BNDTableViewProxyDataSource and the titles in the header are shown correctly (for each section a different title). So far so good. Furthermore the section title contains a dynamic part which is simply the amount of rows in each section (for example -> The section contains 10 rows). Now as the data gets populated the function titleForHeaderInSection in BNDTableViewProxyDataSource gets triggered several times. In this function I'm accessing my view model which is returning the correct amount of rows for each section. But for some reason the section titles are not really updated for each iteration.

While the data is collected and new elements are inserted in my observable array, the mentioned function is triggered now several times and I can see that the constructed section title should start with "The section contains 0 rows" and end with "The section contains 10 rows":

- The section contains 0 rows
- The section contains 1 rows
- The section contains 2 rows
- The section contains 3 rows
.......
...

What I am expecting is that after the last iteration when the title that is returned is "The section contains 10 rows", the appropriate section will reflect also that title but this is not the case. It still shows "The section contains 0 rows".

Any ideas what I'm doing wrong here?

**Comment by srdanrasic** [comment]
Closed as outdated.
