### ISSUE TITLE
Table View With Sections Support

### ISSUE THREAD

**Issue by prefect42** [ReactiveKit/Bond#284]
A common scenario is to have a table view with sections.

As it seems right now an observable array cannot be bound to a table view to supply sections support 

```
extension ObservableArray: DataSourceProtocol {

  public func numberOfSections() -> Int {
    return 1
  }

  public func numberOfElements(inSection section: Int) -> Int {
    return count
  }
}
```

as numberOfSections() always returns 1.

Is support for this planned in the future?

**Comment by srdanrasic** [comment]
Hi @prefect42, yeah, I'm hearing about that often.

In previous versions of Bond it was possible to make ObservableArray of ObservableArrays, but that caused more issues than it solved. It had very complicated object/dependency graph so that feature has been removed in Bond 5.

However, DataSourceProtocol and DataSourceEventKind in Bond 5 are designed to support sections. It would be easy to make something like ObservableSectionedArray.

Let me try to make an example in next few days.

**Comment by yuvalt** [comment]
+1 for an example. Thanks :-)

**Comment by srdanrasic** [comment]
Ok guys, since this is often requested feature I decided to push it into Bond v5 initial release. `v5.0.0-beta8` introduces new type - `Observable2DArray`. It's section array whose indices are IndexPaths so it supports sections.

Please check out [new section in Readme](https://github.com/SwiftBond/Bond#observable2darray--mutableobservable2darray).

Any feedback is welcome!

**Comment by prefect42** [comment]
🎉 Thanks

**Comment by jonathanfoster** [comment]
If anyone comes across this issue, the section @srdanrasic referenced has now moved to https://github.com/DeclarativeHub/Bond/blob/master/Documentation/ObservableCollections.md#observable2darray--mutableobservable2darray.
