### ISSUE TITLE
Migrating from 4.x -> 6.x, unsure of BNDTableViewProxyDataSource

### ISSUE THREAD

**Issue by xLegoz** [ReactiveKit/Bond#394]
I'm currently migrating an app (unfortunately it hasn't been updated in almost a year) and it's got a number of uses for `BNDTableViewProxyDataSource`. There doesn't seem to be documentation on it and no information on a migration path for that type. I'm also not completely familiar with Bond which doesn't help. If you have any advice on what a good migration path is, that would be super helpful!

**Comment by srdanrasic** [comment]
One would conform to `BNDTableViewProxyDataSource` to implement methods not supported by Bond like section headers and footers and action commits.

If you need to provide section headers or footer, create an objects that conforms to protocol `TableViewBond` and pass that to the binding call instead of `createCell` closure. Check out my answer here: https://github.com/ReactiveKit/Bond/issues/257#issuecomment-258863323. It talks about animations, but same the concept applies.

If you need to implement some other methods from the `UITableViewDataSource` protocol, like `tableView:canEditRowAt:`, conform to `UITableViewDataSource` protocol as you normally would and implement it like this:

```swift
extension MyViewController: UITableViewDataSource {

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        fatalError("Implemented by bindings.")
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        fatalError("Implemented by bindings.")
    }

    func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
}
```

First two methods will never be called as they are implemented by the bindings so you can provide a dummy implementation to silence the compiler.

Finally, instead of setting table view data source, set a proxy for reactive data source.

```swift
tableView.reactive.dataSource.forwardTo = self
```

Hope this helps.

**Comment by softvision-catalinmustata** [comment]
So... what happened to `shouldReloadInsteadOfUpdateTableView`? I'm trying to migrate a older project that was using Bond 4.x to 6.x and Swift 3 and I cannot find any reference on where this got moved (or if it's needed anymore)

**Comment by srdanrasic** [comment]
@softvision-catalinmustata you can use non-animated binding to achieve that:

```swift
data.bind(to: tableView, animated: false) {... }
```

**Comment by softvision-catalinmustata** [comment]
Ah, I understand the connection. However, ```public func bind<B : TableViewBond where B.DataSource == DataSource>(to tableView: UITableView, using bond: B) -> Disposable``` does not have an `animated` property (`TableViewBond`) doesn't seem to have one either

**Comment by srdanrasic** [comment]
Hmm, there has to be. Maybe Xcode does not show it because it is defaulted.

https://github.com/ReactiveKit/Bond/blob/master/Sources/UIKit/UITableView.swift#L114

**Comment by softvision-catalinmustata** [comment]
Yes, I noticed that one, but I need to use the second function, that receives a TableViewBond object and doesn't have the animated property.

**Comment by srdanrasic** [comment]
Ah, so you have a custom implementation :) In that case just implement `apply` like this:

https://github.com/ReactiveKit/Bond/blob/master/Sources/UIKit/UITableView.swift#L104

**Comment by softvision-catalinmustata** [comment]
Yes, there's one place that needs a custom implementation. However the old method returned false, so I'd assume I need to work with `beginUpdate` and `endUpdates` instead of `reloadData()`
