### ISSUE TITLE
Can't find to NSTextField

### ISSUE THREAD

**Issue by timothyarmes** [ReactiveKit/Bond#400]
Hi, 

I can't bind to an NSTextField (Mac). Am I doing something wrong?

````
@IBOutlet weak var emailField: NSTextField!
let emailAddress = Observable<String?>(nil)

...

emailAddress.bidirectionalBind(to: emailField)
````

gives me: `NSTextField! does not conform to SignalProtocol`

I also tried:

````
emailAddress.bidirectionalBind(to: emailField.reactive.stringValue)
````

Which gives

````
String<Bond> does not conform to SignalProtocol
````

**Comment by srdanrasic** [comment]
Hi @timothyarmes,

`emailField.reactive.stringValue` is of type `Bond<String>`, while your observable is `String?`. For bidirectional binding to work, both must be of same type. Unfortunately Swift is not very good at error messages sometimes.

That being said, you probably want to bidirectionally bind to  `emailField.reactive.editingString` because that one gets changed when user inputs text.

Hope this helps :)

**Comment by timothyarmes** [comment]
Thank you, that worked.

I think the README documentation needs updating, since all the examples use UITextField's `text` property directly. It's not obvious that the same approach isn't used for NSTextField.
