### ISSUE TITLE
ObservableArray binding to UITableView prevents editing

### ISSUE THREAD

**Issue by Burtan** [ReactiveKit/Bond#413]
Hi,

when I bind my array to an UITableView instead of overriding the functions.

```
override func numberOfSections(in tableView: UITableView) -> Int
override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell 
```

Swiping to edit does not work anymore for the cells, even when implementing
```
override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
```

**Comment by srdanrasic** [comment]
Hi @Burtan,

When you bind to a table view, the binding sets itself as a data source, so your data source does not get called. 

What you have to do is set `tableView.reactive.dataSource.forwardTo = self` to forward the invocations that the binding does not handle to your own object that conforms to `UITableViewDataSource`. You will still need to provide required methods (numberOfRowsInSection and cellForRowAt), but you can just have a dummy implementation since they will not actually be called.

**Comment by Burtan** [comment]
Thanks for the fast response, I understand.
