### ISSUE TITLE
V4-> V6: Bind a reactive.text to something fails

### ISSUE THREAD

**Issue by gilazr** [ReactiveKit/Bond#448]
Hi,
I'm migrating my code from V4 to V6. I used bnd_text in many places in my code both as a feeding signal and as a fed one. I realized that as opposed to bnd_X, reactive.X objects aren't signals but Bond objects. As far as I could tell Bond objects can be written to, but not read from. 

How can I use a label's text for both reading and writing (see migrated code below)

`recommendationsCounterLabel.reactive.text.map { $0?.isEmpty ?? true }.bind(to:recommendationsCounterLabel.reactive.isHidden).dispose(in: reactive.bag)`

This gives compilation error: Value of type 'Bond<String?>' (aka 'Bond<Optional<String>>') has no member 'map'

**Comment by srdanrasic** [comment]
Hey man!

This is expected behaviour - it's logical because labels generate no events (as opposed to text fields for example) so there is no need for such mechanism.

A way to solve it is to feed `recommendationsCounterLabel.reactive.isHidden` from the same place you are feeding `recommendationsCounterLabel.reactive.text`.

```swift
let text = Property<String>(...)

...

text.bind(to: recommendationsCounterLabel.reactive.text)
text.map { $0?.isEmpty ?? true }.bind(to: recommendationsCounterLabel.reactive.isHidden)
```

Hope this helps.

**Comment by gilazr** [comment]
Thanks for your response :)
In V4 it was bidirectional. I was wondering if this functionality was removed on purpose.

Thank you.
